#!/command/with-contenv bash
# SPDX-FileCopyrightText: © 2024 Dave Conroy <dave@tiredofit.ca>
#
# SPDX-License-Identifier: MIT

source /container/base/functions/container/init
output_off
prepare_service single
PROCESS_NAME="secrets"

if var_true "${CONTAINER_ENABLE_SECRETS}" ; then
    call toi_configure_secrets_${CONTAINER_SECRETS_BACKEND,,}_init
else
    service_stop "$(basename "$0")"
fi

liftoff
output_on

## This can probably go in 99 for all we care
#if var_true "${CONTAINER_ENABLE_SECRETS}" ; then
#    case "${CONTAINER_SECRETS_BACKEND,,}" in
#        "infisical" )
#            if var_true "${INFISICAL_DELETE_ENV}" ; then
#                rm -rf /assets/defaults/777-infisical
#            fi
#        ;;
#    esac
#fi
