#!/command/with-contenv bash
# SPDX-FileCopyrightText: © 2024 Dave Conroy <dave@tiredofit.ca>
#
# SPDX-License-Identifier: MIT

source /container/base/functions/container/init
output_off
prepare_service single
PROCESS_NAME="metrics"

if var_true "${CONTAINER_ENABLE_METRICS}" ; then
    :
else
    :
fi

liftoff
output_on