#!/command/with-contenv bash
# SPDX-FileCopyrightText: © 2024 Dave Conroy <dave@tiredofit.ca>
#
# SPDX-License-Identifier: MIT

source /container/base/functions/container/init
output_off
prepare_service single
PROCESS_NAME="messaging"

if var_true "${CONTAINER_ENABLE_MESSAGING}" ; then
    call toi_configure_messaging_${CONTAINER_MESSAGING_BACKEND,,}_init
else
    service_stop "$(basename "$0")"
fi

liftoff
output_on