#!/usr/bin/with-contenv bash

### Timezone Setup
if [ -n "$TIMEZONE" ]; then 
    set_timezone () {
      if [ -f /usr/share/zoneinfo/$TIMEZONE ];  then
        echo "**** [timezone] Setting timezone to $1"
        cp -R /usr/share/zoneinfo/$1 /etc/localtime
        echo $1 > /etc/timezone
        dpkg-reconfigure -f noninteractive tzdata
      else
        echo "**** [timezone] ERROR: Timezone $1 does not exist - Skipping.."
      fi
    } 

    if [ ! -d /usr/share/zoneinfo ];  then
      apt-get update
      apt-get install -y tzdata
      set_timezone $TIMEZONE
      apt-get clean
      apt-get purge -y tzdata
      rm -rf /var/lib/apt/lists/*
    else
      set_timezone $TIMEZONE
    fi
fi


  mkdir -p /tmp/state
  touch /tmp/state/99-container-init
