#!/command/with-contenv bash

source /assets/functions/00-container
output_off
SERVICE_NAME="timezone"

### Timezone setup
if [ -n "${TIMEZONE}" ]; then
    set_timezone "${TIMEZONE}"
fi

liftoff
output_on